package bicicletes;
// Generated 14/02/2017 00:11:33 by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;


/**
 * Estacio generated by hbm2java
 */
public class Estacio implements java.io.Serializable {

	private int numEst;
	private String nomEst;
	private Boolean activa;
	private ArrayList<Posicio> posicios = new ArrayList<Posicio>(0);

	public Estacio() {
	}

	public Estacio(int numEst) {
		this.numEst = numEst;
	}

	public Estacio(int numEst, String nomEst, Boolean activa, ArrayList<Posicio> posicios) {
		this.numEst = numEst;
		this.nomEst = nomEst;
		this.activa = activa;
		this.posicios = posicios;
	}

	public int getNumEst() {
		return this.numEst;
	}

	public void setNumEst(int numEst) {
		this.numEst = numEst;
	}

	public String getNomEst() {
		return this.nomEst;
	}

	public void setNomEst(String nomEst) {
		this.nomEst = nomEst;
	}

	public Boolean getActiva() {
		return this.activa;
	}

	public void setActiva(Boolean activa) {
		this.activa = activa;
	}

	public ArrayList<Posicio> getPosicios() {
		return this.posicios;
	}

	public void setPosicios(ArrayList<Posicio> posicios) {
		this.posicios = posicios;
	}

}
