package bicicletes;
// Generated 14/02/2017 00:11:33 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Posicio generated by hbm2java
 */
public class Posicio implements java.io.Serializable {

	private Estacio estacio;
	private int numP;
	private Bicicleta bicicleta;
	private Boolean bloquejada;
	private Date dataP;

	public Posicio() {
	}

	public Posicio(Estacio estacio,int numP) {
		this.estacio = estacio;
		this.numP=numP;
	}

	public Posicio(Estacio estacio,int numP, Bicicleta bicicleta, Boolean bloquejada, Date dataP) {
		this.estacio = estacio;
		this.numP=numP;
		this.bicicleta = bicicleta;
		this.bloquejada = bloquejada;
		this.dataP = dataP;
	}


	public Estacio getEstacio() {
		return this.estacio;
	}

	public void setEstacio(Estacio estacio) {
		this.estacio = estacio;
	}

	public int getNumP() {
		return this.numP;
	}

	public void setNumP(int numP) {
		this.numP = numP;
	}

	public Bicicleta getBicicleta() {
		return this.bicicleta;
	}

	public void setBicicleta(Bicicleta bicicleta) {
		this.bicicleta = bicicleta;
	}

	public Boolean getBloquejada() {
		return this.bloquejada;
	}

	public void setBloquejada(Boolean bloquejada) {
		this.bloquejada = bloquejada;
	}

	public Date getDataP() {
		return this.dataP;
	}

	public void setDataP(Date dataP) {
		this.dataP = dataP;
	}

}
