package classesEnergia;
// Generated 15/02/2017 10:10:18 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private int num;
	private String nom;
	private BigDecimal habitants;
	private Set<ProduccioEnergia> produccioEnergias = new HashSet<ProduccioEnergia>(0);

	public Pais() {
	}

	public Pais(int num) {
		this.num = num;
	}

	public Pais(int num, String nom, BigDecimal habitants, Set<ProduccioEnergia> produccioEnergias) {
		this.num = num;
		this.nom = nom;
		this.habitants = habitants;
		this.produccioEnergias = produccioEnergias;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public BigDecimal getHabitants() {
		return this.habitants;
	}

	public void setHabitants(BigDecimal habitants) {
		this.habitants = habitants;
	}

	public Set<ProduccioEnergia> getProduccioEnergias() {
		return this.produccioEnergias;
	}

	public void setProduccioEnergias(Set<ProduccioEnergia> produccioEnergias) {
		this.produccioEnergias = produccioEnergias;
	}

}
